const forDeveloperPricing = {
  monthly: [
    {
      type: 'STARTER',
      price: 4990,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '10 photos per project',
      ],
      features: [
        'Properties description',
        'Photos gallery',
        'Email',
        'Call now',
        'Whatsapp',
        'Contact information',
        'Schedule a visit',
        'Real Estate Agency’s Logo',
        'Agent’s photo on listing',
        'Street view',
        'Reviews',
        'Similar listing',
        'Available date',
        'CRM tools access',
        'KYC & AML checking (add-on 25 AED per verification)',
        'Contract management (add-on on demand)',
        'Short Term Rental Platform access',
        'Loyalty Program access',
      ],
    },
    {
      type: 'GROWTH',
      price: 7490,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '50 photos per project',
      ],
      features: [
        'STARTER’s features',
        '10 Featured listings',
        'Video',
        'Virtual tour',
        'Tour request',
        'Floor plan',
        'Nearby',
        'Walkscore',
        'Calculate travel time',
        'Property cost average',
        'Property size average',
        'Mortgage calculator',
        'PDF property',
        'Landlord list',
        'Dashboard datas',
      ],
    },
    {
      type: 'UNLIMITED',
      price: 9990,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '100 photos per project',
      ],
      features: [
        'GROWTH’s features',
        '100 Featured listings',
        'Verified listings',
      ],
    },
  ],
  annually: [
    {
      type: 'STARTER',
      price: 4290,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '10 photos per project',
      ],
      features: [
        'Properties description',
        'Photos gallery',
        'Email',
        'Call now',
        'Whatsapp',
        'Contact information',
        'Schedule a visit',
        'Real Estate Agency’s Logo',
        'Agent’s photo on listing',
        'Street view',
        'Reviews',
        'Similar listing',
        'Available date',
        'CRM tools access',
        'KYC & AML checking (add-on 25 AED per verification)',
        'Contract management (add-on on demand)',
        'Short Term Rental Platform access',
        'Loyalty Program access',
      ],
    },
    {
      type: 'GROWTH',
      price: 6490,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '50 photos per project',
      ],
      features: [
        'STARTER’s features',
        '10 Featured listings',
        'Video',
        'Virtual tour',
        'Tour request',
        'Floor plan',
        'Nearby',
        'Walkscore',
        'Calculate travel time',
        'Property cost average',
        'Property size average',
        'Mortgage calculator',
        'PDF property',
        'Landlord list',
        'Dashboard datas',
      ],
    },
    {
      type: 'UNLIMITED',
      price: 8690,
      details: [
        'per month for 1 year contract(monthly payment)',
        '1 project',
        '1 year duration per project',
        '100 photos per project',
      ],
      features: [
        'GROWTH’s features',
        '100 Featured listings',
        'Verified listings',
      ],
    },
  ],
};

export default forDeveloperPricing;
